// Root layout

// Analytics
import { SpeedInsights } from "@vercel/speed-insights/next";

// Data types
import { ReactNode } from "react";

// Metadata & Fonts
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../styling/globals.css";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Justin Abuyuan",
  description: "Generated by create next app",
};

// Theme provider
import ThemeProvider from "@/components/theme/ThemeProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
